[general]
live_config_reload = true
working_directory = "/Users/mfischbach/"

import = [ "~/.config/alacritty/toml/general.toml",
           "~/.config/alacritty/toml/window.toml",
           "~/.config/alacritty/toml/font.toml",
           "~/.config/alacritty/toml/colors.toml", ]
