# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# colors:
#   primary:
#     background: "#161616"
#     foreground: "#ffffff"
#   search:
#     matches:
#       foreground: CellBackground
#       background: '#ee5396'
#     footer_bar:
#       background: '#262626'
#       foreground: '#ffffff'
#   normal:
#     black: "#262626"
#     magenta: "#ff7eb6"
#     green: "#42be65"
#     yellow: "#ffe97b"
#     blue: "#33b1ff"
#     red: "#ee5396"
#     cyan: "#3ddbd9"
#     white: "#dde1e6"
#   bright:
#     black: "#393939"
#     magenta: "#ff7eb6"
#     green: "#42be65"
#     yellow: "#ffe97b"
#     blue: "#33b1ff"
#     red: "#ee5396"
#     cyan: "#3ddbd9"
#     white: "#ffffff"
