[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular"}
bold = { style = "Regular" }
italic = { style = "Regular" }
bold_italic = { style = "Regular" }
size = 18
offset = { x = 2, y = 2 }
builtin_box_drawing = false
