[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular"}
bold = { style = "bold" }
italic = { style = "italic" }
bold_italic = { style = "bold" }
size = 15
offset = { x = 1, y = 1 }
builtin_box_drawing = false
