[terminal.shell]
program = "/bin/zsh"
# which tmux
args = ["-l", "-c", "/opt/homebrew/bin/tmux new-session -A -s main"]
# args = ["-l"]

[bell]
duration = 300
color = "#ebdbb2"

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 200
blink_timeout = 100
unfocused_hollow = true
thickness = 0.20

[cursor.style]
shape = "Block"
blinking = "On"

