[window]
dimensions = { columns = 100, lines  = 35 }
# position = "None"
# padding = { x = 2, y = 2 }
# dynamic_padding = true
decorations = "Buttonless"
# opacity = 1.0
# blur = false 
# startup_mode = "Windowed"
title = "Terminal"

