[colors]
line_indicator = { foreground = "#ebdbb2", background = "#504945" }
footer_bar = { foreground = "#ebdbb2", background = "#1d2021" }
selection = { text = "#fbf1c7", background = "#665c54" }

[colors.primary]
foreground = "#ebdbb2"
background = "#282828"
dim_foreground = "#bdae93"
bright_foreground = "#fbf1c7"
# cursor = { text = "#282828", cursor = "#ebdbb2" }
# vi_mode_cursor = { text = "#282828", cursor = "#ebdbb2" }

[colors.search]
matches = { foreground = "#ebdbb2", background = "#d65d0e" }
focused_match = { foreground = "#ebdbb2", background = "#fe8019" }

[colors.hints]
start = { foreground = "#928374", background = "#282828" }
end = { foreground = "#928374", background = "#282828" }

[colors.normal]
black = "#282828" 
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#82a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

