[shell]
program = "/bin/zsh"
args = ["-l"]

[bell]
duration = 300
color = "#ebdbb2"

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false
# thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

