#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# styling settings
yabai -m config window_shadow                float

yabai -m config menubar_opacity              0.5
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config window_animation_duration    0.0

yabai -m config insert_feedback_color        0xfffbf1c7

# yabai -m config external_bar                 off:40:0

# window settings
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

yabai -m config window_insertion_point       focused
yabai -m config window_origin_display        focused
yabai -m config window_zoom_persist          off

# mouse settings
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config focus_follows_mouse          autoraise

# layout settings
yabai -m config layout                       bsp
yabai -m config window_placement             second_child
yabai -m config auto_balance                 on
yabai -m config split_ratio                  0.60 # only when autobalance off
yabai -m config split_type                   auto

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^OmniDiskSweeper$" manage=off

echo "yabai configuration loaded..."
