#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# global settings
yabai -m config                                 \
    window_placement             second_child   \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  3              \
    bottom_padding               3              \
    left_padding                 3              \
    right_padding                3              \
    window_gap                   3              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    focus_follows_mouse          autoraise      \
    window_opacity               off            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.93           \
    window_shadow                on             \

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Finder$" manage=off

borders active_color=0xf0fbf1c7 inactive_color=0x00000000 width=3.0 hidpi=on &

echo "yabai configuration loaded.."
